# Generated by Django 5.1.5 on 2025-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='date_1',
            field=models.DateField(blank=True, null=True, verbose_name='1本目'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='date_2',
            field=models.DateField(blank=True, null=True, verbose_name='2本目'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='date_3',
            field=models.DateField(blank=True, null=True, verbose_name='3本目'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='date_4',
            field=models.DateField(blank=True, null=True, verbose_name='4本目'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='weight_1',
            field=models.FloatField(blank=True, null=True, verbose_name='1回目の体重'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='weight_2',
            field=models.FloatField(blank=True, null=True, verbose_name='2回目の体重'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='weight_3',
            field=models.FloatField(blank=True, null=True, verbose_name='3回目の体重'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='weight_4',
            field=models.FloatField(blank=True, null=True, verbose_name='4回目の体重'),
        ),
    ]
