# Generated by Django 5.1.5 on 2025-01-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_alter_childmodel_date_1_alter_childmodel_date_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodel',
            name='ad_date',
            field=models.DateField(blank=True, null=True, verbose_name='種親羽化日'),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='date_5',
            field=models.DateField(blank=True, null=True, verbose_name='羽化日'),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='種親サイズ'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='割り出し日'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='gener',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='累代'),
        ),
    ]
