# Generated by Django 5.1.5 on 2025-01-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0001_initial'),
        ('child', '0003_childmodel_ad_date_childmodel_date_5_childmodel_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='size',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='size_ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_ad', to='adult.adultmodel'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='ad_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_date', to='adult.adultmodel'),
        ),
    ]
