# Generated by Django 5.1.5 on 2025-01-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_remove_childmodel_size_childmodel_size_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='ad_date',
            field=models.DateField(blank=True, null=True, verbose_name='種親羽化日'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='size_ad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='種親サイズ'),
        ),
    ]
